### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/e-commerce#133]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] product_links_goodies
- [x] product_multi_link - By @reinka - #185 
- [x] website_sale_cart_selectable - By @chienandalu - #192 
- [ ] website_sale_category_megamenu
- [x] website_sale_checkout_country_vat - By @Yajo - #187 
- [ ] website_sale_checkout_skip_payment - By @eLBati - #203
- [x] website_sale_default_country - By @Yajo - #183 
- [ ] website_sale_order_company - By @reinka - #180 
- [ ] website_sale_product_brand - By @loxamir - #136 
- [ ] website_sale_recently_viewed_products - By @reinka - #184 
- [x] website_sale_require_legal - By @Yajo - #205 
- [x] website_sale_require_login - By @iledarn - #138 
- [x] website_sale_suggest_create_account - By @ovnicraft - #172 
- [ ] website_sale_vat_required
- [x] website_sale_wishlist - By @reinka - #181

**Comment by LeartS** [comment]
Why is the wishlist module missing from here?

**Comment by pedrobaeza** [comment]
Because it was added after the 10.0 branch creation. I have manually added it.

**Comment by reinka** [comment]
PR for `website_sale_order_company`: #180

**Comment by reinka** [comment]
Could anybody maybe please update the list above? ~~It seems~~ 
~~`product_links_goodies`~~
~~`product_multi_link `~~
~~`website_sale_category_megamenu`~~
~~`website_sale_default_country `~~
~~`website_sale_product_brand `~~
~~`website_sale_recently_viewed_products `~~
~~have been already migrated.~~

**Comment by pedrobaeza** [comment]
@reinka I don't see that modules migrated.

**Comment by reinka** [comment]
@pedrobaeza Sorry, my bad. I only concluded from them being available in the `10.0` branch without actually looking at the code... I'll edit my comment.

**Comment by eLBati** [comment]
Porting ```website_sale_checkout_skip_payment``` with https://github.com/OCA/e-commerce/pull/203

**Comment by seancallahan88** [comment]
Why is website_sale_qty missing?

**Comment by pedrobaeza** [comment]
Because it was merged in 9.0 after the 10.0 branch creation. Any way, it was renamed to https://github.com/OCA/e-commerce/tree/10.0/website_sale_price_tier when migrated to 10.0  if I don't remember bad

**Comment by pedrobaeza** [comment]
Triaging.
