### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/e-commerce#208]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] product_links_goodies
- [ ] product_multi_link (see discussion here #210)
- [ ] product_template_multi_link (see discussion here #210)
- [ ] website_sale_affiliate - By @DarkoNikolovski - #232 
- [ ] website_sale_cart_selectable
- [ ] website_sale_category_alphabetic
- [ ] website_sale_category_megamenu - By @remytms - #259 
- [ ] website_sale_checkout_country_vat
- [x] website_sale_checkout_skip_payment - By @larmar - #228 
- [x] website_sale_default_country - By @ernestotejeda - #239 
- [x] website_sale_hide_empty_category - By @remytms - #256 
- [x] website_sale_hide_price - By @AbrahamTrey - #241 
- [ ] website_sale_order_type
- [x] website_sale_product_brand - By @ernestotejeda - #238 
- [ ] website_sale_product_attribute_filter_visibility
- [ ] website_sale_recently_viewed_products
- [ ] website_sale_search_fuzzy
- [x] website_sale_require_legal - By @ernestotejeda  - #237 
- [x] website_sale_require_login - By @oscarolar - #224 
- [x] website_sale_suggest_create_account - By @oscarolar - #225 
- [x] website_sale_vat_required - By @ernestotejeda - #236 
- [ ] website_sale_wishlist

**Comment by legalsylvain** [comment]
Hi @pedrobaeza, I updated your list to mention #210. Regards.

**Comment by larmar** [comment]
Hi @pedrobaeza i will migrate website_sale_checkout_skip_payment to 11.0.
It's missing in the list, I guess its because wip for 10.0

**Comment by pedrobaeza** [comment]
@larmar, added in the list.

**Comment by emagdalenaC2i** [comment]
Please check in the list website_sale_checkout_skip_payment because it is already merged
