### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/e-commerce#683]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] website_account_fiscal_position_partner_type - By @cubells - #1169
- [x] website_sale_attribute_filter_form_submit - By @miguel-S73 - #757
- [x] website_sale_attribute_filter_multiselect - By @miguel-S73 - #758
- [x] website_sale_cart_expire - By @Highcooley - #785
- [x] website_sale_cart_selectable - By @carmenbianca - #977
- [x] website_sale_category_breadcrumb - By @carlos-lopez-tecnativa - #953
- [ ] website_sale_checkout_country_vat
- [x] website_sale_checkout_skip_payment - By @kisuka - #803
- [x] website_sale_comparison_hide_price - By @dsolanki-initos - #794
- [ ] website_sale_hide_empty_category
- [x] website_sale_hide_price - By @JrAdhoc - #716
- [x] website_sale_invoice_address - By @suker - #837
- [x] website_sale_order_type - By @pilarvargas-tecnativa - #826
- [x] website_sale_product_assortment - By @pilarvargas-tecnativa - #873
- [x] website_sale_product_attachment - By @ernesto-garcia-tecnativa - #829
- [x] website_sale_product_attribute_filter_collapse - By @pilarvargas-tecnativa - #825
- [x] website_sale_product_attribute_value_filter_existing - By @anothingguy - #773
- [x] website_sale_product_brand - By @miguel-S73 - #742
- [x] website_sale_product_description - By @matiasperalta1 - #791
- [x] website_sale_product_detail_attribute_image - By @Segui-S73 - #759
- [ ] website_sale_product_detail_attribute_value_image
- [x] website_sale_product_item_cart_custom_qty - By @pilarvargas-tecnativa - #835
- [x] website_sale_product_minimal_price - By @sbiosca-s73 - #857
- [x] website_sale_product_reference_displayed - By @bvanjeelharia - #710
- [x] website_sale_require_legal - By @pilarvargas-tecnativa - #850
- [ ] website_sale_require_login
- [ ] website_sale_secondary_unit
- [x] website_sale_stock_available - By @bvanjeelharia - #708
- [x] website_sale_stock_list_preview - By @ernesto-garcia-tecnativa - #832
- [x] website_sale_stock_provisioning_date - By @ernesto-garcia-tecnativa - #846
- [x] website_sale_suggest_create_account - By @pilarvargas-tecnativa - #836
- [x] website_sale_tax_toggle - By @carlos-lopez-tecnativa - #952
- [x] website_sale_vat_required - By @pilarvargas-tecnativa - #841
- [x] website_sale_wishlist_keep - By @pilarvargas-tecnativa - #831
- [x] website_snippet_product_category - By @pilarvargas-tecnativa - #824

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by jok-adhoc** [comment]
Working on website_sale_suggest_create_account #705

**Comment by mac-adhoc** [comment]
The functionality of _website_sale_require_login_ is now included in v16 as a native feature. Therefore this module could be depreciated.
The new feature included in v16 let you select how is able to checkout on your eCommerce based in 3 different options:

1. Optional.
2. Disabled (buy as guest).
3. Mandatory (no guest checkout)

**Comment by JrAdhoc** [comment]
website_sale_hide_price migration on #716

**Comment by miguel-S73** [comment]
website_sale_product_brand migration on https://github.com/OCA/e-commerce/pull/742

**Comment by valkenpower** [comment]
Possible to add website_sale_tax_toggle to the wishlist ?

**Comment by anothingguy** [comment]
website_sale_product_attribute_value_filter_existing https://github.com/OCA/e-commerce/pull/773

**Comment by dsolanki-initos** [comment]
website_sale_comparison_hide_price

**Comment by dsolanki-initos** [comment]
website_sale_product_description

**Comment by valkenpower** [comment]
Website_tax_toggle

**Comment by liebana** [comment]
Can someone make the 16 branch as the default one?

**Comment by robmarinussen** [comment]
.

**Comment by suker** [comment]
website_sale_invoice_address migration on #837

**Comment by suker** [comment]
website_sale_product_assortment migration on #854

**Comment by danielduqma** [comment]
website_sale_exception migration on #865 

This module is not in the list because its migrations [hasn't been merged](https://github.com/OCA/e-commerce/pulls?q=website_sale_exception) since it was [added to 12.0](https://github.com/OCA/e-commerce/pull/350)

**Comment by yaazkal** [comment]
Hi, I see `website_sale_product_attribute_filter_category` is not listed in the issue, maybe it has been replaced by other module or is just that no one is working on it?

**Comment by flotho** [comment]
> Website_tax_toggle

Hi @valkenpower , did you have any PR for this.
AFAICS, the way Odoo handle price in website has massively changed in v16 and no longer relies on user groups.

**Comment by JrAdhoc** [comment]
website_sale_hide_empty_category migration on #950

**Comment by carlos-lopez-tecnativa** [comment]
website_sale_category_breadcrumb https://github.com/OCA/e-commerce/pull/953

**Comment by huguesdk** [comment]
please add `website_sale_cart_selectable` #977.

**Comment by BarcleyKnight** [comment]
> website_sale_hide_price migration on [#716](https://github.com/OCA/e-commerce/pull/716)

hello, can you update this for 18.0 please?

**Comment by SiscoIngeos** [comment]
website_sale_restrict_by_pricelist #1166
